components:
  - name: uptime-monitor
    image: ghcr.io/liamrandall/uptime-monitor:0.1.0

ingress:
  host: "uptime-monitor.localhost.cosmonic.sh"

hostInterfaces:
  - namespace: wasi
    package: keyvalue
    interfaces:
      - store
  - namespace: wasi
    package: http
    interfaces:
      - outgoing-handler
